<?
$PERM["uzory"]["*"]="R";
$PERM["uzory"]["G6"]="X";
$PERM["upakovka-tovara"]["*"]="D";
$PERM["upakovka-tovara"]["G6"]="X";
$PERM["struktura-artikula"]["*"]="X";
$PERM["struktura-artikula"]["G6"]="X";
$PERM["shipping-and-payment"]["*"]="D";
$PERM["shipping-and-payment"]["G1"]="X";
$PERM["individual-order"]["*"]="D";
$PERM["individual-order"]["G1"]="X";
$PERM["internet-torgovlya"]["*"]="D";
$PERM["internet-torgovlya"]["6"]="X";
$PERM["sety"]["*"]="D";
$PERM["sety"]["6"]="X";
$PERM["postovshchikam"]["*"]="D";
$PERM["postovshchikam"]["6"]="X";
$PERM["postavshchikam"]["*"]="D";
$PERM["postavshchikam"]["6"]="X";
?>