<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("description", "Дамы и Господа, мы рады представить Вам раздел новостей нашего сайта, здесь вы всегда сможете найти актуальную информацию о изменениях в нашей компании, спешите подписаться на рассылку и получайте новости и обновления прямо себе в почту!");
$APPLICATION->SetPageProperty("keywords", "Новости");
$APPLICATION->SetPageProperty("title", "Новости ГХСЗ Гусь-Хрустальный Стекольный Завод (ООО ПромСИЗ) ");
$APPLICATION->SetTitle("Новости");
?><?$APPLICATION->IncludeComponent(
	"bitrix:news",
	"news",
	Array(
		"ADD_ELEMENT_CHAIN" => "Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "Y",
		"CACHE_GROUPS" => "N",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CATALOG_FILTER_NAME" => "arrProductsFilter",
		"CHECK_DATES" => "Y",
		"DETAIL_ACTIVE_DATE_FORMAT" => "j F Y",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_FIELD_CODE" => array("PREVIEW_TEXT","DETAIL_TEXT","DETAIL_PICTURE","DATE_ACTIVE_FROM",""),
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_TITLE" => "",
		"DETAIL_PROPERTY_CODE" => array("LINK_GOODS","FORM_QUESTION","FORM_ORDER","PHOTOPOS","LINK_SERVICES","LINK_STUDY","VIDEO","PHOTOS","DOCUMENTS",""),
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DETAIL_STRICT_SECTION_CHECK" => "Y",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "N",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_TYPE_VIEW" => "element_1",
		"FILE_404" => "",
		"FILTER_FIELD_CODE" => array("",""),
		"FILTER_NAME" => "arRegionLink",
		"FILTER_PROPERTY_CODE" => array("",""),
		"FORM_ID_ORDER_SERVISE" => "",
		"GALLERY_PROPERTY" => "MORE_PHOTO",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"HIDE_NOT_AVAILABLE" => "N",
		"IBLOCK_CATALOG_TYPE" => "aspro_next_catalog",
		"IBLOCK_ID" => "15",
		"IBLOCK_TYPE" => "aspro_next_content",
		"IMAGE_POSITION" => "left",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"IS_VERTICAL" => "N",
		"LINE_ELEMENT_COUNT_LIST" => "3",
		"LINKED_ELEMENST_PAGE_COUNT" => "20",
		"LINKED_PRODUCTS_PROPERTY" => "LINK",
		"LIST_ACTIVE_DATE_FORMAT" => "j F Y",
		"LIST_FIELD_CODE" => array("NAME","PREVIEW_TEXT","PREVIEW_PICTURE","DATE_ACTIVE_FROM",""),
		"LIST_PROPERTY_CODE" => array("PERIOD",""),
		"LIST_VIEW" => "slider",
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => "20",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "main",
		"PAGER_TITLE" => "",
		"PERIOD_PROPERTY" => "PERIOD",
		"PREVIEW_TRUNCATE_LEN" => "",
		"PRICE_CODE" => array(),
		"PRICE_PROPERTY" => "PRICE",
		"SECTION_ELEMENTS_TYPE_VIEW" => "list_elements_1",
		"SEF_FOLDER" => "/company/news/",
		"SEF_MODE" => "Y",
		"SEF_URL_TEMPLATES" => Array("detail"=>"#ELEMENT_CODE#/","news"=>"","section"=>""),
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"SHOW_404" => "N",
		"SHOW_BACK_LINK" => "Y",
		"SHOW_DETAIL_LINK" => "Y",
		"SHOW_FAQ_BLOCK" => "Y",
		"SHOW_FILTER_DATE" => "N",
		"SHOW_GALLERY" => "Y",
		"SHOW_LINKED_PRODUCTS" => "Y",
		"SHOW_NEXT_ELEMENT" => "N",
		"SHOW_PERIOD" => "N",
		"SHOW_PRICE" => "N",
		"SHOW_SERVICES_BLOCK" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"STORES" => array("",""),
		"STRICT_SECTION_CHECK" => "Y",
		"S_ASK_QUESTION" => "",
		"S_ORDER_SERVISE" => "",
		"T_DOCS" => "",
		"T_GALLERY" => "",
		"T_GOODS" => "Товары по акции",
		"T_NEXT_LINK" => "",
		"T_PREV_LINK" => "",
		"T_SERVICES" => "",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "Y",
		"USE_PERMISSIONS" => "N",
		"USE_RATING" => "N",
		"USE_REVIEW" => "N",
		"USE_RSS" => "N",
		"USE_SEARCH" => "N",
		"USE_SHARE" => "Y"
	)
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>