<?
$PERM["pokupatelyam"]["*"]="X";
$PERM["pokupatelyam"]["G6"]="X";
$PERM["o-promsiz"]["*"]="X";
$PERM["o-promsiz"]["G6"]="X";
$PERM["sertifikaty"]["*"]="X";
$PERM["sertifikaty"]["G6"]="X";
$PERM["staff"]["*"]="D";
$PERM["staff"]["G1"]="X";
$PERM["postavshchikam"]["*"]="D";
$PERM["postavshchikam"]["6"]="X";
$PERM["exhibition-activity"]["*"]="D";
$PERM["exhibition-activity"]["G1"]="X";
$PERM["production"]["*"]="D";
$PERM["production"]["G1"]="X";
$PERM["history"]["*"]="D";
$PERM["history"]["G1"]="X";
?>